### PR TITLE
Fix classic build and recognize SERIES parameter

### PR DESCRIPTION
**Pull request by toabctl**
This fixes:
( cd "/home/tom/devel/snapcore/pc-amd64-gadget/stage"/tmp && \
    apt-get download -o APT::Architecture=amd64 $( apt-cache \
    -o APT::Architecture=amd64 showpkg shim-signed | sed -n \
    -e 's/^Package: *//p' | sort -V | tail -1 ); )
E: Can't find a source to download version '1.52+15.7-0ubuntu1' \
    of 'shim-signed:amd64'
make: *** [Makefile:92: boot] Error 100

### CODE REVIEW

**Comment by xnox** [comment]
This looks closer to what the core gadget does. Not sure if you want to be a bit more explicit in terms of pulling from `$(SERIES)-updates`, since `$(SERIES)` defaults to `$(SERIES)-proposed` as during key rotations we probably want to build out of -updates.

**Comment by toabctl** [comment]
> This looks closer to what the core gadget does. Not sure if you want to be a bit more explicit in terms of pulling from `$(SERIES)-updates`, since `$(SERIES)` defaults to `$(SERIES)-proposed` as during key rotations we probably want to build out of -updates.

If I explicitly tell what pocket to use (eg `updates`), I get:
```
$ pull-lp-debs -a amd64 -D ubuntu shim-signed jammy-updates
Source package lookup failed, trying lookup of binary package shim-signed
The binary package 'shim-signed' does not exist in the Ubuntu primary archive for architecture amd64 in jammy-Updates with status in Pending, Published
The source package 'shim-signed' does not exist in the Ubuntu primary archive in jammy-Updates with status in Pending, Published
```

I could make the pocket configurable. would that be an option?

**Comment by toabctl** [comment]
@xnox thoughts?

**Comment by toabctl** [comment]
friendly ping ...

**Comment by lool** [comment]
Hi, I think this merge https://github.com/snapcore/pc-gadget/commit/c7ffd47badd7342ddb9d79b9be808ea10e1c0fc7 fixes all issues that this pull request was addressing – so perhaps we can close this one

**Comment by xnox** [comment]
> > This looks closer to what the core gadget does. Not sure if you want to be a bit more explicit in terms of pulling from `$(SERIES)-updates`, since `$(SERIES)` defaults to `$(SERIES)-proposed` as during key rotations we probably want to build out of -updates.
> 
> If I explicitly tell what pocket to use (eg `updates`), I get:
> 
> ```
> $ pull-lp-debs -a amd64 -D ubuntu shim-signed jammy-updates
> Source package lookup failed, trying lookup of binary package shim-signed
> The binary package 'shim-signed' does not exist in the Ubuntu primary archive for architecture amd64 in jammy-Updates with status in Pending, Published
> The source package 'shim-signed' does not exist in the Ubuntu primary archive in jammy-Updates with status in Pending, Published
> ```
> 

@toabctl  did you make a typo? jammy-Updates (uppercase U) is not a valid pocket, jammy-updates (lowercase u) is.

```console
$ pull-lp-debs -a amd64 -D ubuntu shim-signed jammy-updates
Found shim-signed 1.51.3 in jammy
Downloading shim-signed_1.51.3+15.7-0ubuntu1_amd64.deb from archive.ubuntu.com (0.636 MiB)
[=====================================================>]100%
```

**Pull request closed without merging**
